<a href="https://colab.research.google.com/github/akshansh9336/Akshansh-Singh/blob/main/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world akshansh");

hello world akshansh

In [ ]:
print("akshansh");

akshansh

In [ ]:
a=2
b=10
print(a+b)
print(a%b)
print(a*b)
print(a/b)
print(type(a))

12
2
20
0.2
<class 'int'>

In [ ]:
name = input("Enter your name")
print(name)
age = input('Enter your age')
print(age)

Enter your nameakshansh
akshansh
Enter your age100
100

In [ ]:
college = input("Enter college name")
print(college)
address = input("Enter college address")
print(address)

Enter college nameShri ram swaroop memorial college of engineering and management
Shri ram swaroop memorial college of engineering and management
Enter college addressTiwariganj
Tiwariganj

In [ ]:
#type casting
a=("10")
print(int(a))

10

In [ ]:
#upeer case conversion
name = ("akshansh singh")
print(name.upper())
len(name) #name length
print(name.replace("singh","raj")) #rreplacing name

AKSHANSH SINGH
akshansh raj

In [ ]:
#all should lie in same line
marks=int(input("enter marks"))
if marks>90:
   print("A")
elif marks>80:
   print("B")
elif marks>70:
   print("C")
elif marks>60:
   print("D")
elif marks>50:
   print("E")
else:
   print("fail")

enter marks70
D

In [ ]:
# divisiblity test for 5
num=int(input("enter a number"))
if num%5==0:
   print("divisible")
else:
   print("not")

enter a number65
divisible

In [ ]:
# divisiblity test for 3
num=int(input("input a number"))
if num%3==0:
   print("divisible")
else:
   print("not divisible by 3")

input a number22
not divisible by 3

In [ ]:
# both 5 and 3 test
num=int(input("enter a number"))
if num%5==0 and num%3==0:
   print("divisible")
else:
   print("not")

enter a number30
divisible

In [ ]:
num=int(input("enter a number"))
if num%5==0 and num%3==0:
   print("divisible by both")
elif num%3==0:
   print ("divisible by 3")
elif num%5==0:   print("divisible by 5")
else:
   prit("No

In [ ]:
#atm withdrawal
balance=int(input("Enter you current balance"));
money=int(input("Enter the amount:"))
if money<=balance:
  print("withdrawal successfull")
else:
  print("insufficient balance")

Enter you current balance3456
Enter the amount:34555
insufficient balance

In [ ]:
#password check
password=(input("Enter you current password"));
passkey=(input("Enter the passkey:"))
if password==passkey:
  print("successfull")
else:
  print("declined")

Enter you current passwordHello
Enter the passkey:Hello
successfull

In [ ]:
#Check digits in number
num=(input("enter the number"))
length = len(num)
if length==2:
  print("double digit")
elif length==3:
  print("triple digit")
elif length==4:
  print("chaupal digit")
else:
  print("bs kr")

enter the number56485
bs kr

In [ ]:
for i in range(20):
 print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19

In [ ]:
for i in range(5,51,5):
 print(i)

5
10
15
20
25
30
35
40
45
50

In [ ]:
for i in range(10,-11,-1):
 print(i)

10
9
8
7
6
5
4
3
2
1
0
-1
-2
-3
-4
-5
-6
-7
-8
-9
-10

In [ ]:
for i in range(1,10):
  if i==6:
    break
  print (i)

1
2
3
4
5

In [ ]:
for i in range(1,10):
 if i==6:
   continue
 print(i)
#here 6 is skipped because of continue

1
2
3
4
5
7
8
9

In [ ]:
a=12
b=11
a,b=b,a

In [ ]:
#calculator
digits=input(number of digits you want to calculate MAX 3 DIGITS)
if digits=

In [ ]:
name = "Akshansh"
print(name[0:4:4])

A

In [ ]:
#palidrome
name="Akshansh"
print(name[::-1])

hsnahskA

In [ ]:
name="Akshansh"
print(name*5)

AkshanshAkshanshAkshanshAkshanshAkshansh

In [ ]:
name="Akshansh"
title="Singh"
print(name+"_"+title)
print("Ansh"in name)

Akshansh_Singh
False

In [ ]:
name="Akshansh"
title="Singh"
print(name.upper())
print(name.lower())
print(name.title())
print(name.capitalize())
print(name.replace("Akshansh","Singh"))

AKSHANSH
akshansh
Akshansh
Akshansh
Singh

In [ ]:
name="Akshansh Singh"
print(name.split())
print(name.find("n"))
print(name.count("h"))
print(len(name))

['Akshansh', 'Singh']
5
3
14

In [ ]:
a=[10,20,30]
b=[20,30]
print(a+b)
print(a[0])
print(a[0:2])
print([10,20]*3)
print(20 in [10,20,30])
a.extend([40,50])
print(a)
a.remove(40)
print(a)
a=[30,60,90]
print(a)

[10, 20, 30, 20, 30]
10
[10, 20]
[10, 20, 10, 20, 10, 20]
True
[10, 20, 30, 40, 50]
[10, 20, 30, 50]
[30, 60, 90]

In [ ]:
# one dimensiional data
import pandas as pd


marks = pd.Series([85,90,78,95])
print(marks)

0    85
1    90
2    78
3    95
dtype: int64

In [ ]:
# 2-d data

student={
    "name":["Rahul","Amait","Priya"],
    "age":[20,21,19],
    "Marks":[80,90,95]
}

df=pd.DataFrame(student)

print(df)

    name  age  Marks
0  Rahul   20     80
1  Amait   21     90
2  Priya   19     95

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Zomato-data-.csv')

In [ ]:
df

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining
147,Vijayalakshmi,Yes,No,3.9/5,47,200,Dining

In [ ]:
df.tail()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining
147,Vijayalakshmi,Yes,No,3.9/5,47,200,Dining

In [ ]:
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

In [ ]:
df.sample(5)

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
128,Mohitesh Hut Roll,No,No,3.3/5,0,150,Dining
105,Cakes & Slices,No,No,3.5/5,13,300,Dining
73,LSD Cafe,No,No,2.9/5,84,700,other
39,Maruthi Davangere Benne Dosa,Yes,No,4.0/5,17,150,Dining
56,Banashankari Donne Biriyani,Yes,No,3.8/5,104,300,Dining

In [ ]:
df.shape

(148, 7)

In [ ]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes',
       'approx_cost(for two people)', 'listed_in(type)'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         148 non-null    object
 1   online_order                 148 non-null    object
 2   book_table                   148 non-null    object
 3   rate                         148 non-null    object
 4   votes                        148 non-null    int64
 5   approx_cost(for two people)  148 non-null    int64
 6   listed_in(type)              148 non-null    object
dtypes: int64(2), object(5)
memory usage: 8.2+ KB

In [ ]:
df["name"]

0                      Jalsa
1             Spice Elephant
2            San Churro Cafe
3      Addhuri Udupi Bhojana
4              Grand Village
               ...
143         Melting Melodies
144          New Indraprasta
145             Anna Kuteera
146                   Darbar
147            Vijayalakshmi
Name: name, Length: 148, dtype: object

In [ ]:
import pandas as pd

data = {
    "Emp_ID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Aman","Neha","Rahul","Priya","Karan",
             "Simran","Mohit","Anjali","Vikas","Pooja"],
    "Age": [24,25,23,28,30,26,27,24,29,25],
    "Department": ["HR","IT","Sales","IT","HR",
                   "Finance","Sales","IT","Finance","HR"],
    "Salary": [35000,50000,45000,60000,38000,
               55000,47000,62000,58000,40000],
    "City": ["Delhi","Lucknow","Noida","Delhi","Jaipur",
             "Noida","Lucknow","Delhi","Jaipur","Delhi"]
}

df = pd.DataFrame(data)

print(df)

   Emp_ID    Name  Age Department  Salary     City
0     101    Aman   24         HR   35000    Delhi
1     102    Neha   25         IT   50000  Lucknow
2     103   Rahul   23      Sales   45000    Noida
3     104   Priya   28         IT   60000    Delhi
4     105   Karan   30         HR   38000   Jaipur
5     106  Simran   26    Finance   55000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
7     108  Anjali   24         IT   62000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
9     110   Pooja   25         HR   40000    Delhi

In [ ]:
df.head()

   Emp_ID   Name  Age Department  Salary     City
0     101   Aman   24         HR   35000    Delhi
1     102   Neha   25         IT   50000  Lucknow
2     103  Rahul   23      Sales   45000    Noida
3     104  Priya   28         IT   60000    Delhi
4     105  Karan   30         HR   38000   Jaipur

In [ ]:
df.tail()

   Emp_ID    Name  Age Department  Salary     City
5     106  Simran   26    Finance   55000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
7     108  Anjali   24         IT   62000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
9     110   Pooja   25         HR   40000    Delhi

In [ ]:
df.sample()

   Emp_ID   Name  Age Department  Salary     City
6     107  Mohit   27      Sales   47000  Lucknow

In [ ]:
df.shape

(10, 6)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
 5   City        10 non-null     object
dtypes: int64(3), object(3)
memory usage: 612.0+ bytes

In [ ]:
df.describe()

          Emp_ID        Age        Salary
count   10.00000  10.000000     10.000000
mean   105.50000  26.100000  49000.000000
std      3.02765   2.330951   9580.071909
min    101.00000  23.000000  35000.000000
25%    103.25000  24.250000  41250.000000
50%    105.50000  25.500000  48500.000000
75%    107.75000  27.750000  57250.000000
max    110.00000  30.000000  62000.000000

In [ ]:
df.dtypes

Emp_ID         int64
Name          object
Age            int64
Department    object
Salary         int64
City          object
dtype: object

In [ ]:
df["Name"]

0      Aman
1      Neha
2     Rahul
3     Priya
4     Karan
5    Simran
6     Mohit
7    Anjali
8     Vikas
9     Pooja
Name: Name, dtype: object

In [ ]:
df[["Name","Salary"]]

     Name  Salary
0    Aman   35000
1    Neha   50000
2   Rahul   45000
3   Priya   60000
4   Karan   38000
5  Simran   55000
6   Mohit   47000
7  Anjali   62000
8   Vikas   58000
9   Pooja   40000

In [ ]:
df[df["Salary"]>5000]

   Emp_ID    Name  Age Department  Salary     City
0     101    Aman   24         HR   35000    Delhi
1     102    Neha   25         IT   50000  Lucknow
2     103   Rahul   23      Sales   45000    Noida
3     104   Priya   28         IT   60000    Delhi
4     105   Karan   30         HR   38000   Jaipur
5     106  Simran   26    Finance   55000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
7     108  Anjali   24         IT   62000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
9     110   Pooja   25         HR   40000    Delhi

In [ ]:
df[df["Department"] == "IT"]

   Emp_ID    Name  Age Department  Salary     City
1     102    Neha   25         IT   50000  Lucknow
3     104   Priya   28         IT   60000    Delhi
7     108  Anjali   24         IT   62000    Delhi

In [ ]:
df.sort_values(by='Salary')

   Emp_ID    Name  Age Department  Salary     City
0     101    Aman   24         HR   35000    Delhi
4     105   Karan   30         HR   38000   Jaipur
9     110   Pooja   25         HR   40000    Delhi
2     103   Rahul   23      Sales   45000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
1     102    Neha   25         IT   50000  Lucknow
5     106  Simran   26    Finance   55000    Noida
8     109   Vikas   29    Finance   58000   Jaipur
3     104   Priya   28         IT   60000    Delhi
7     108  Anjali   24         IT   62000    Delhi

In [ ]:
df["Salary"].sum()

np.int64(490000)

In [ ]:
df["Name"].count()

np.int64(10)

In [ ]:

df["Department"].unique()

array(['HR', 'IT', 'Sales', 'Finance'], dtype=object)

In [ ]:
df["Department"].nunique()

4

In [ ]:
df["Bonus"]=df["Salary"]*0.5
df

   Emp_ID    Name  Age Department  Salary     City    Bonus
0     101    Aman   24         HR   35000    Delhi  17500.0
1     102    Neha   25         IT   50000  Lucknow  25000.0
2     103   Rahul   23      Sales   45000    Noida  22500.0
3     104   Priya   28         IT   60000    Delhi  30000.0
4     105   Karan   30         HR   38000   Jaipur  19000.0
5     106  Simran   26    Finance   55000    Noida  27500.0
6     107   Mohit   27      Sales   47000  Lucknow  23500.0
7     108  Anjali   24         IT   62000    Delhi  31000.0
8     109   Vikas   29    Finance   58000   Jaipur  29000.0
9     110   Pooja   25         HR   40000    Delhi  20000.0

In [ ]:
df.rename(columns={'Name': 'Emp_name'}, inplace=True)

In [ ]:
df

   Emp_ID Emp_name  Age Department  Salary     City    Bonus
0     101     Aman   24         HR   35000    Delhi  17500.0
1     102     Neha   25         IT   50000  Lucknow  25000.0
2     103    Rahul   23      Sales   45000    Noida  22500.0
3     104    Priya   28         IT   60000    Delhi  30000.0
4     105    Karan   30         HR   38000   Jaipur  19000.0
5     106   Simran   26    Finance   55000    Noida  27500.0
6     107    Mohit   27      Sales   47000  Lucknow  23500.0
7     108   Anjali   24         IT   62000    Delhi  31000.0
8     109    Vikas   29    Finance   58000   Jaipur  29000.0
9     110    Pooja   25         HR   40000    Delhi  20000.0

In [ ]:
df.drop("Bonus",axis=1,inplace=True)
df.isnull()

   Emp_ID  Emp_name    Age  Department  Salary   City
0   False     False  False       False   False  False
1   False     False  False       False   False  False
2   False     False  False       False   False  False
3   False     False  False       False   False  False
4   False     False  False       False   False  False
5   False     False  False       False   False  False
6   False     False  False       False   False  False
7   False     False  False       False   False  False
8   False     False  False       False   False  False
9   False     False  False       False   False  False

In [ ]:
df.isnull().sum()

Emp_ID        0
Emp_name      0
Age           0
Department    0
Salary        0
City          0
dtype: int64

In [ ]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Emp_name'].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Emp_name, dtype: bool

In [ ]:
df[df["City"] == "Delhi"]

   Emp_ID Emp_name  Age Department  Salary   City
0     101     Aman   24         HR   35000  Delhi
3     104    Priya   28         IT   60000  Delhi
7     108   Anjali   24         IT   62000  Delhi
9     110    Pooja   25         HR   40000  Delhi